### ISSUE TITLE
Mock api for testing

### ISSUE THREAD

**Issue by rovast** [ztalab/ZAPortal#35]
## Overview

Add mock server for ci testing.

## TODO

- [ ] Add mock server
- [ ] Add testing cases
- [ ] Add ci jobs

## Reference

- [Github doc](https://docs.github.com/cn/issues/tracking-your-work-with-issues/about-task-lists)
